-- Q1.
SELECT STAND_NAME, UPPER(STAND_NAME) AS STAND_UPPER, LOWER(STAND_NAME), INITCAP(STAND_NAME) AS STAND_TITLE
    FROM STAND_USER;

-- Q2.
SELECT USER_NAME, CATCHPHRASE, LENGTH(CATCHPHRASE) AS PHRASE_LENGTH
    FROM STAND_USER
    ORDER BY PHRASE_LENGTH desc;

-- Q3.
SELECT STAND_NAME, SUBSTR(STAND_NAME, 0, 8) AS STAND_SHORT
    FROM STAND_USER;

-- Q4
SELECT STAND_NAME, INSTR(UPPER(STAND_NAME), 'WORLD') AS WORLD_POSITION
    FROM STAND_USER;

-- Q5
SELECT USER_NAME, LPAD(POWER, 8, '*') AS POWER_BAR
    FROM STAND_USER;

-- Q6
SELECT USER_NAME, POWER, ROUND(POWER, -2) AS ROUNDED_POWER, TRUNC(POWER, -2) AS TRUNCATED_POWER, MOD(POWER, 300) AS POWER_MOD_300
    FROM STAND_USER;

-- Q7
SELECT USER_NAME, NVL2(PRECISION, TO_CHAR(PRECISION), 'Unknown') AS PRECISION_STATUS
    FROM STAND_USER;

-- Q8
SELECT USER_NAME, DEBUT_DATE, NEXT_DAY((ADD_MONTHS(DEBUT_DATE, 6)), 'MONDAY') AS TRAINING_REVIEW
    FROM STAND_USER;

-- Q9
SELECT USER_NAME, ROUND(MONTHS_BETWEEN(SYSDATE, DEBUT_DATE), 0) AS MONTHS_SINCE_DEBUT
    FROM STAND_USER
    ORDER BY MONTHS_SINCE_DEBUT;

-- Q10
SELECT USER_NAME, STAND_NAME, CONCAT(USER_NAME, CONCAT(' wields ', CONCAT(STAND_NAME, CONCAT(' with power ', CONCAT(TO_CHAR(power), CONCAT(', but dreams of ', TO_CHAR(power*3, '9,999'))))))) AS DREAM_STATEMENT
    FROM STAND_USER;

-- Q11
SELECT STAND_NAME
    FROM STAND_USER
    WHERE REGEXP_LIKE(STAND_NAME, 'WORLD', 'i');

-- Q12
SELECT USER_NAME, STAND_NAME, SOUNDEX(STAND_NAME) AS SOUND_CODE
    FROM STAND_USER;
